version: "3.7"
       
networks:
  spark-network:

volumes:
  spark-apps:
  spark-data:

services:
  spark-master:
    image: spark-master:2.4.4
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks: 
      spark-network:
    volumes:
       - spark-apps:/opt/spark-apps
       - spark-data:/opt/spark-data
    environment:
      - "SPARK_LOCAL_IP=spark-master"

  spark-worker-1:
    image: spark-worker:2.4.4
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_LOCAL_IP=spark-worker-1"
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_CORES=1"
      - "SPARK_WORKER_MEMORY=1G"
      - "SPARK_DRIVER_MEMORY=128m"
      - "SPARK_EXECUTOR_MEMORY=256m"
    networks: 
      spark-network:
    volumes:
       - spark-apps:/opt/spark-apps
       - spark-data:/opt/spark-data

  spark-worker-2:
    image: spark-worker:2.4.4
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_LOCAL_IP=spark-worker-2"
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_CORES=1"
      - "SPARK_WORKER_MEMORY=1G"
      - "SPARK_DRIVER_MEMORY=128m"
      - "SPARK_EXECUTOR_MEMORY=256m"
    networks: 
      spark-network:
    volumes:
       - spark-apps:/opt/spark-apps
       - spark-data:/opt/spark-data

  spark-worker-3:
    image: spark-worker:2.4.4
    container_name: spark-worker-3
    hostname: spark-worker-3
    depends_on:
      - spark-master
    ports:
      - "8083:8081"
    environment:
      - "SPARK_LOCAL_IP=spark-worker-3"
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_CORES=1"
      - "SPARK_WORKER_MEMORY=1G"
      - "SPARK_DRIVER_MEMORY=128m"
      - "SPARK_EXECUTOR_MEMORY=256m"
    networks: 
      spark-network:
    volumes:
       - spark-apps:/opt/spark-apps
       - spark-data:/opt/spark-data
